version: '2'
services:
  airfile-server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=airfile-api.dawei.io
      - LETSENCRYPT_HOST=airfile-api.dawei.io
      - VIRTUAL_PORT=8080
      - GIN_MODE=release
      - "ENV=${ENV}"
      - "AWS_REGION=${AWS_REGION}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "MONGODB_USERNAME=${MONGODB_USERNAME}"
      - "MONGODB_PASSWORD=${MONGODB_PASSWORD}"
      - "MONGODB_ENDPOINT=${MONGODB_ENDPOINT}"
      - "REDIRECT_URL=${REDIRECT_URL}"

networks:
    default:
      name: nginx-proxy
      external: true
